// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";

Jest.describe("Expect", (function (param) {
        Jest.test("toBe", (function (param) {
                return Jest.Expect.toBe(Jest.Expect.expect(3), 3);
              }));
      }));

Jest.describe("Expect.Operators", (function (param) {
        Jest.test("==", (function (param) {
                return Curry._2(Jest.Expect.Operators.$eq$eq, Jest.Expect.expect(3), 3);
              }));
      }));

export {
  
}
/*  Not a pure module */
