// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function hey(param) {
  return "hello";
}

var Test = {
  hey: hey
};

var test = "hello";

exports.Test = Test;
exports.test = test;
/* No side effect */
