// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Express = require("express");

var app = Express();

app.get("/unlimited", (function (param, res) {
        res.status(200).send("Unlimited! Let's go!");
      }));

app.get("/limited", (function (param, res) {
        res.status(200).send("Limited, don't over use me!");
      }));

app.listen(8080);

exports.app = app;
/* app Not a pure module */
