// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(param) {
  var dict = Object.fromEntries([]);
  return {
          get: (function (key) {
              return Promise.resolve(dict[key]);
            }),
          set: (function (key, value) {
              dict[key] = value;
              return Promise.resolve(undefined);
            })
        };
}

async function get(dict, identifier) {
  return dict[identifier];
}

async function set(dict, identifier, value) {
  dict[identifier] = value;
}

var InMemoryStore = {
  make: make,
  get: get,
  set: set
};

exports.InMemoryStore = InMemoryStore;
/* No side effect */
