// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var Store = require("./Store.bs.js");

Jest.describe("InMemoryStore", (function (param) {
        Jest.testPromise("get", undefined, (function (param) {
                var store = Store.InMemoryStore.make(10);
                return Store.InMemoryStore.get(store, "id123").then(function (value) {
                            return Jest.Expect.toEqual(Jest.Expect.expect(value), 10);
                          });
              }));
      }));

/*  Not a pure module */
