// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function timeDiffInSeconds(date1, date2) {
  return (Math.abs(date1.getTime() - date2.getTime()) | 0) / 1000 | 0;
}

exports.timeDiffInSeconds = timeDiffInSeconds;
/* No side effect */
