// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function timeDiffInSeconds(date1, date2) {
  return (Math.abs(date1.getTime() - date2.getTime()) | 0) / 1000 | 0;
}

function limitTo(max, value) {
  return Math.max(0.0, Math.min(max, value)) | 0;
}

function make(num) {
  if (num > 0) {
    return num;
  }
  
}

function value(x) {
  return x;
}

var NaturalNumber = {
  make: make,
  value: value
};

exports.timeDiffInSeconds = timeDiffInSeconds;
exports.limitTo = limitTo;
exports.NaturalNumber = NaturalNumber;
/* No side effect */
